### ISSUE TITLE
Detect runtime version from global.json file

### ISSUE THREAD

**Issue by mpoiron** [ronaldbosma/InstallNetCoreRuntimeAndHostingTask#5]
First of all thank you, this task is really a great help to ensure the server has all required software to run our app.

It would be great if it could check the required version from a [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x) file in the project. This could be presented in the form of a **Use global json** parameter just like the [Use .NET Core task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops).

What are your thoughts on this ?

**Comment by ronaldbosma** [comment]
Hi @mpoiron. I'm not sure if I understand the scenario you're asking for. Where would the global.json be stored/come from?

**Comment by mpoiron** [comment]
I guess the file would be stored in the repository, along with the .NET Core project using it.

**Comment by ronaldbosma** [comment]
Hi @mpoiron. 

I don't think this will be a feature that will be added because:
- The InstallNetCoreRuntimeAndHosting task is expected to be executed in a release pipeline or in a deployment job in a YAML pipeline. In that situation you normally won't have access to a repository, which means you can't access the repository.
- I think in many cases there will be multiple services/sites in on the same server in IIS that depend on the .NET Core Runtime & Hosting Bundle. It would make sense to me to create a separate pipeline with the sole purpose of updating .NET Core. Which means it's separate of repositories containing a .NET Core project.
